import type { IconType } from 'react-icons'
import {
  GiCastle,
  GiSwordman,
  GiCrossedSwords,
  GiShield,
  GiPineTree,
  GiMountainRoad,
  GiCaveEntrance,
  GiSailboat,
  GiDragonHead,
  GiSkullCrossedBones,
  GiPotionBall,
  GiTreasureMap,
  GiChest,
  GiCampfire,
  GiGate,
  GiTowerFlag,
  GiVillage,
  GiForestCamp,
  GiRiver,
  GiDesert,
  GiVolcano,
  GiStoneBridge,
  GiShintoShrine,
  GiAncientRuins,
  GiSwamp,
  GiCrown,
  GiBattleAxe,
  GiBowArrow,
  GiBookCover,
  GiScrollUnfurled,
  GiKeyring,
  GiGoldBar,
  GiGems,
  GiAnvil,
  GiWoodenDoor,
  GiBrickWall,
  GiStoneTower,
  GiHutsVillage,
  GiWindmill,
  GiWheat,
  GiFishingPole,
  GiWolfHead,
  GiBearHead,
  GiSpiderWeb,
  GiBatWing,
  GiGhost,
  GiGraveyard,
  GiTombstone,
  GiStoneThrone,
  GiWaterfall,
  GiCauldron,
  GiWoodenCrate,
  GiCompass,
  GiMountains,
  GiLighthouse,
  GiWell,
  GiAnchor,
} from 'react-icons/gi'

export interface MapIconOption {
  key: string
  label: string
  Icon: IconType
}

/** Curated GameIcons (via react-icons/gi) usable as a tile's glyph — a hand
 *  picked subset rather than the whole ~4000-icon set, so the picker stays
 *  a simple grid instead of needing full-text search over everything. */
export const MAP_ICONS: MapIconOption[] = [
  { key: 'GiCastle', label: 'Castle', Icon: GiCastle },
  { key: 'GiSwordman', label: 'Warrior', Icon: GiSwordman },
  { key: 'GiCrossedSwords', label: 'Battle', Icon: GiCrossedSwords },
  { key: 'GiShield', label: 'Shield', Icon: GiShield },
  { key: 'GiPineTree', label: 'Tree', Icon: GiPineTree },
  { key: 'GiMountainRoad', label: 'Mountain Road', Icon: GiMountainRoad },
  { key: 'GiCaveEntrance', label: 'Cave', Icon: GiCaveEntrance },
  { key: 'GiSailboat', label: 'Boat', Icon: GiSailboat },
  { key: 'GiDragonHead', label: 'Dragon', Icon: GiDragonHead },
  { key: 'GiSkullCrossedBones', label: 'Danger', Icon: GiSkullCrossedBones },
  { key: 'GiPotionBall', label: 'Potion', Icon: GiPotionBall },
  { key: 'GiTreasureMap', label: 'Treasure Map', Icon: GiTreasureMap },
  { key: 'GiChest', label: 'Chest', Icon: GiChest },
  { key: 'GiCampfire', label: 'Campfire', Icon: GiCampfire },
  { key: 'GiGate', label: 'Gate', Icon: GiGate },
  { key: 'GiTowerFlag', label: 'Tower', Icon: GiTowerFlag },
  { key: 'GiVillage', label: 'Village', Icon: GiVillage },
  { key: 'GiForestCamp', label: 'Forest Camp', Icon: GiForestCamp },
  { key: 'GiRiver', label: 'River', Icon: GiRiver },
  { key: 'GiDesert', label: 'Desert', Icon: GiDesert },
  { key: 'GiVolcano', label: 'Volcano', Icon: GiVolcano },
  { key: 'GiStoneBridge', label: 'Bridge', Icon: GiStoneBridge },
  { key: 'GiShintoShrine', label: 'Shrine', Icon: GiShintoShrine },
  { key: 'GiAncientRuins', label: 'Ruins', Icon: GiAncientRuins },
  { key: 'GiSwamp', label: 'Swamp', Icon: GiSwamp },
  { key: 'GiCrown', label: 'Crown', Icon: GiCrown },
  { key: 'GiBattleAxe', label: 'Axe', Icon: GiBattleAxe },
  { key: 'GiBowArrow', label: 'Bow', Icon: GiBowArrow },
  { key: 'GiBookCover', label: 'Book', Icon: GiBookCover },
  { key: 'GiScrollUnfurled', label: 'Scroll', Icon: GiScrollUnfurled },
  { key: 'GiKeyring', label: 'Key', Icon: GiKeyring },
  { key: 'GiGoldBar', label: 'Gold', Icon: GiGoldBar },
  { key: 'GiGems', label: 'Gems', Icon: GiGems },
  { key: 'GiAnvil', label: 'Anvil', Icon: GiAnvil },
  { key: 'GiWoodenDoor', label: 'Door', Icon: GiWoodenDoor },
  { key: 'GiBrickWall', label: 'Wall', Icon: GiBrickWall },
  { key: 'GiStoneTower', label: 'Stone Tower', Icon: GiStoneTower },
  { key: 'GiHutsVillage', label: 'Huts', Icon: GiHutsVillage },
  { key: 'GiWindmill', label: 'Windmill', Icon: GiWindmill },
  { key: 'GiWheat', label: 'Farmland', Icon: GiWheat },
  { key: 'GiFishingPole', label: 'Fishing', Icon: GiFishingPole },
  { key: 'GiWolfHead', label: 'Wolf', Icon: GiWolfHead },
  { key: 'GiBearHead', label: 'Bear', Icon: GiBearHead },
  { key: 'GiSpiderWeb', label: 'Spider', Icon: GiSpiderWeb },
  { key: 'GiBatWing', label: 'Bat', Icon: GiBatWing },
  { key: 'GiGhost', label: 'Ghost', Icon: GiGhost },
  { key: 'GiGraveyard', label: 'Graveyard', Icon: GiGraveyard },
  { key: 'GiTombstone', label: 'Tombstone', Icon: GiTombstone },
  { key: 'GiStoneThrone', label: 'Throne', Icon: GiStoneThrone },
  { key: 'GiWaterfall', label: 'Waterfall', Icon: GiWaterfall },
  { key: 'GiCauldron', label: 'Cauldron', Icon: GiCauldron },
  { key: 'GiWoodenCrate', label: 'Crate', Icon: GiWoodenCrate },
  { key: 'GiCompass', label: 'Compass', Icon: GiCompass },
  { key: 'GiMountains', label: 'Mountains', Icon: GiMountains },
  { key: 'GiLighthouse', label: 'Lighthouse', Icon: GiLighthouse },
  { key: 'GiWell', label: 'Well', Icon: GiWell },
  { key: 'GiAnchor', label: 'Anchor', Icon: GiAnchor },
]

export const MAP_ICONS_BY_KEY: Record<string, MapIconOption> = Object.fromEntries(
  MAP_ICONS.map((opt) => [opt.key, opt]),
)
